//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_USER
    {
        public int ID { get; set; }
        public string ACCOUNT { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> MA_NHAN_SU { get; set; }
        public string NAME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string AVATAR { get; set; }
        public Nullable<int> ID_PHONG_BAN { get; set; }
        public Nullable<System.DateTime> NGAY_TAO { get; set; }
        public string NGUOI_TAO { get; set; }
        public Nullable<System.DateTime> NGAY_CAP_NHAT { get; set; }
        public string NGUOI_CAP_NHAT { get; set; }
        public string SESSION_TOKEN { get; set; }
        public string SALT { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
    }
}
