//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevApps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BLOCKCHAINEntities : DbContext
    {
        public BLOCKCHAINEntities()
            : base("name=BLOCKCHAINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN_USER> ADMIN_USER { get; set; }
        public virtual DbSet<CONTACT> CONTACTs { get; set; }
        public virtual DbSet<LEADER_TEAM> LEADER_TEAM { get; set; }
        public virtual DbSet<COMPANY_ADDRESS> COMPANY_ADDRESS { get; set; }
        public virtual DbSet<COMPANY_INFOR> COMPANY_INFOR { get; set; }
        public virtual DbSet<BANNER> BANNERs { get; set; }
        public virtual DbSet<POSITION> POSITIONs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<NEWS> NEWS { get; set; }
    }
}
