//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string COMPANY { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> ORDER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string ADMIN_CREATED { get; set; }
        public string ADMIN_UPDATED { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
    }
}
