//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string CODE { get; set; }
        public string PHONE { get; set; }
        public string COMPANY { get; set; }
        public string EMAIL { get; set; }
        public string DESCRIPTIONS { get; set; }
        public Nullable<bool> CHECK { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ADMIN_CREATE { get; set; }
        public string ADMIN_UPDATE { get; set; }
    }
}
